name: Kanban Board Automation

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed, merged]

jobs:
  update-project:
    runs-on: ubuntu-latest

    steps:
      - name: Move issue to "In Progress" when PR is linked
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            const projectNumber = 1;
            const columnName = "In Progress";
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            const issue = await github.rest.issues.listEvents({
              owner,
              repo,
              issue_number
            });

            console.log(`Moving issue ${issue_number} to ${columnName}`);

      - name: Move issue to "Done" when closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const projectNumber = 1;
            const columnName = "Done";
            console.log(`Issue cerrado: moviendo a columna ${columnName}`);
